### ISSUE TITLE
resource manifest generation

### ISSUE THREAD

**Issue by nmiculinic** [kubermatic/bulward#42]
In the kubecarrier, we package operator components as deployable manifests, https://github.com/kubermatic/kubecarrier/tree/master/pkg/internal/resources  . Since bulward is operator library in a way, we need packaging it the same way that kubecarrier, kubermatic, and other projects can easily consume it, and deploy it as a dependency.

**Comment by jiachengxu** [comment]
For doing that, I would like to migrate these 2 packages to our util repo, since these are heavily used in resource pkg:
https://github.com/kubermatic/kubecarrier/tree/master/pkg/internal/kustomize
https://github.com/kubermatic/kubecarrier/tree/master/pkg/internal/reconcile

**Comment by nmiculinic** [comment]
https://github.com/kubermatic/kubecarrier/tree/master/pkg/internal/kustomize this one you can migrate, with a small caveat. The 

```
func (k *kustomizeContext) Build(path string) ([]unstructured.Unstructured, error)
```

should be
```
func (k *kustomizeContext) Build(path string) ([]runtime.Object, error)
```

and the objects where possible should be cast to `runtime.Object` proper type via the scheme. (i.e. `scheme.New(...); scheme.Convert(...)` 

For this one: https://github.com/kubermatic/kubecarrier/tree/master/pkg/internal/reconcile I still think it has design issues, and I dislike it. If we're going to migrate it now would be a good time having improvement talks about its API.
