### ISSUE TITLE
Roles/RoleBindings name collision.

### ISSUE THREAD

**Issue by jiachengxu** [kubermatic/bulward#58]
Both OrganizationRoleTemplate and ProjectRoleTemplate can create Roles/RoleBindings in Project namespace. Currently, the name of Roles/RoleBindings is the same as the name of OrganizationRoleTemplate/ProjectRoleTemplate, this can lead name collision if OrganizationRoleTemplate and ProjectRoleTempalte have the same name.

## Possible solution
Add `organization-` and `project-` prefix to the name of roles/rolebindings.

**Comment by nmiculinic** [comment]
This looks good to me. 

Btw, do we set created role's name reference in the object's status?

**Comment by jiachengxu** [comment]
> Btw, do we set created role's name reference in the object's status?

No, currently, we don't do that, but I think we can add that status field, so it will be easier to track and manage

**Comment by nmiculinic** [comment]
exactly, it would be easier to track  & manage. 

Another possible solution is using `generateName` for kube-apiserver to guarantee uniqueness. 

One other alternative would be generating name via hashing unique attributes (or even appending generating objects UID/shortened UID/hashed UID)
